name: CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Test
        run: |
          poetry run pytest --cov=commitomatic --cov-report=xml
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key python --value-file $PWD/coverage.xml
          rate=$(grep -Pio 'line-rate="\K[^"]*' coverage.xml | head -n1)
          percentage=$(echo "100 * $rate" | bc)
          percentage_rounded=$(printf "%.f" $percentage)
          echo "lines=${percentage_rounded}" >> $GITHUB_OUTPUT
          echo "path=${BADGE_PATH}" >> $GITHUB_OUTPUT
          echo "branch=badges" >> $GITHUB_OUTPUT
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
          BADGE_PATH: ${{ steps.extract_branch.outputs.branch }}/test-badge.svg
