name: CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root
      - name: Test
        run: poetry run pytest
